org.gradle.jvmargs=-Xmx4G -XX:MaxMetaspaceSize=512m -XX:+HeapDumpOnOutOfMemoryError
android.useAndroidX=true
android.enableJetifier=true

# Hỗ trợ 16KB page size cho Google Play Store yêu cầu
android.enableR8.fullMode=true
android.useFullClasspathForDexingTransform=true

# Tối ưu hóa cho 16KB page size
android.native.buildOutput=verbose